# Generated by Django 4.2.19 on 2025-02-24 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0083_measure_radar_exclude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pcn",
            options={"ordering": ["name"]},
        ),
    ]
